#!/usr/bin/env python
"""Evaluate LightGBM models on forward validation folds.

Modes:
    direct   -- features only (Phase 1 diagnostic)
    stacked  -- features + strict-OOF incumbent prediction
    residual -- predict (y - incumbent) on h=1,3; use incumbent elsewhere

Usage:
    python scripts/evaluate_lgbm.py --mode direct
    python scripts/evaluate_lgbm.py --mode stacked
    python scripts/evaluate_lgbm.py --mode residual
    python scripts/evaluate_lgbm.py --mode residual --unweighted
"""

from __future__ import annotations

import argparse
import json
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

import numpy as np
import pandas as pd

from ts_forecasting.baseline_registry import (
    BASELINE_CONFIGS,
    build_predictor,
    build_transformer,
)
from ts_forecasting.constants import (
    CODE_COLUMN,
    HORIZON_COLUMN,
    ID_COLUMN,
    SUB_CATEGORY_COLUMN,
    SUB_CODE_COLUMN,
    TARGET_COLUMN,
    TIME_COLUMN,
    WEIGHT_COLUMN,
    detect_feature_columns,
)
from ts_forecasting.evaluation import (
    aggregate_result_summaries,
    finalize_stress_block,
    initialize_stress_accumulator,
    summarize_scored_predictions,
    update_stress_accumulator,
)
from ts_forecasting.io import get_columns, get_max_ts_index, read_parquet_frame
from ts_forecasting.lgbm_models import (
    DEFAULT_PARAMS,
    LGBMForecaster,
    PreparedFeatureFrame,
    build_seen_sub_code_pairs,
    prepare_feature_frame,
)
from ts_forecasting.sequential import IdentityTransformer, SequentialInferencePipeline
from ts_forecasting.validation import (
    annotate_cold_start_rows,
    build_expanding_window_folds,
    build_first_seen_lookup,
    ExpandingWindowFold,
)

INCUMBENT_CONFIG_NAME = (
    "ridge_oofnorm_pentaslice_h13_s008_q85_a50_unweighted_v1"
)
COLD_START_KEY = [CODE_COLUMN, SUB_CODE_COLUMN]
DEFAULT_RESIDUAL_HORIZONS = [1, 3]


# ---------------------------------------------------------------------------
# OOF incumbent predictions (Codex fix #2: no target leakage)
# ---------------------------------------------------------------------------


def _fit_predict_incumbent(
    train_frame: pd.DataFrame,
    predict_frame: pd.DataFrame,
    config: dict[str, object],
) -> np.ndarray:
    """Fit incumbent on *train_frame*, return predictions on *predict_frame*."""
    pipeline = SequentialInferencePipeline(
        transformer=IdentityTransformer(),
        predictor=build_predictor(config),
    ).fit(train_frame)
    preds_df = pipeline.predict(predict_frame)
    merged = predict_frame[[ID_COLUMN]].merge(
        preds_df[[ID_COLUMN, "prediction"]], on=ID_COLUMN, how="left",
    )
    return merged["prediction"].to_numpy(dtype=float)


def build_oof_incumbent_predictions(
    train_frame: pd.DataFrame,
    config: dict[str, object],
    *,
    oof_holdout_steps: int = 360,
    oof_step_size: int = 360,
    oof_min_train_steps: int = 1000,
) -> pd.Series:
    """Build strict out-of-fold incumbent predictions for training data.

    Uses expanding-window sub-folds within *train_frame* so that each
    row's incumbent prediction was generated by a model that never saw
    that row's target.  Rows not covered by any sub-fold holdout are NaN
    and should be excluded from LightGBM training.
    """
    max_ts = int(train_frame[TIME_COLUMN].max())
    # Maximise sub-folds: compute how many fit
    available = max_ts - oof_holdout_steps - oof_min_train_steps
    max_n_folds = max(1, available // oof_step_size + 1) if available >= 0 else 0
    if max_n_folds == 0:
        return pd.Series(np.nan, index=train_frame.index, dtype=float)
    try:
        sub_folds = build_expanding_window_folds(
            max_ts_index=max_ts,
            holdout_steps=oof_holdout_steps,
            n_folds=max_n_folds,
            step_size=oof_step_size,
            min_train_steps=oof_min_train_steps,
        )
    except ValueError:
        return pd.Series(np.nan, index=train_frame.index, dtype=float)

    oof_preds = pd.Series(np.nan, index=train_frame.index, dtype=float)
    ts = train_frame[TIME_COLUMN]

    for sub_fold in sub_folds:
        sub_train = train_frame[ts <= sub_fold.train_end_ts]
        sub_valid_mask = (
            (ts > sub_fold.train_end_ts)
            & (ts <= sub_fold.validation_end_ts)
        )
        sub_valid = train_frame[sub_valid_mask]
        if len(sub_valid) == 0:
            continue

        preds = _fit_predict_incumbent(sub_train, sub_valid, config)
        oof_preds.loc[sub_valid_mask] = preds

    return oof_preds


def build_precomputed_oof_cache_path(
    cache_dir: str | Path,
    *,
    incumbent_name: str,
    train_path: str,
    oof_holdout_steps: int = 360,
    oof_step_size: int = 360,
    oof_min_train_steps: int = 1000,
) -> Path:
    cache_root = Path(cache_dir)
    cache_root.mkdir(parents=True, exist_ok=True)
    train_stem = Path(train_path).stem
    cache_name = (
        f"{train_stem}_{incumbent_name}"
        f"_h{oof_holdout_steps}_s{oof_step_size}_m{oof_min_train_steps}.parquet"
    )
    return cache_root / cache_name


def write_precomputed_oof_cache(cache_path: str | Path, oof_series: pd.Series) -> None:
    cache_frame = pd.DataFrame(
        {
            "row_index": oof_series.index.to_numpy(),
            "prediction": oof_series.to_numpy(dtype=float),
        }
    )
    Path(cache_path).parent.mkdir(parents=True, exist_ok=True)
    cache_frame.to_parquet(cache_path, index=False)


def load_precomputed_oof_cache(cache_path: str | Path) -> pd.Series:
    cache_frame = pd.read_parquet(cache_path)
    return pd.Series(
        cache_frame["prediction"].to_numpy(dtype=float),
        index=cache_frame["row_index"].to_numpy(),
        dtype=float,
    )


def resolve_precomputed_train_oof(
    *,
    cache_dir: str | Path,
    train_path: str,
    incumbent_name: str,
    train_frame: pd.DataFrame,
    incumbent_config: dict[str, object],
    oof_holdout_steps: int = 360,
    oof_step_size: int = 360,
    oof_min_train_steps: int = 1000,
) -> pd.Series:
    cache_path = build_precomputed_oof_cache_path(
        cache_dir,
        incumbent_name=incumbent_name,
        train_path=train_path,
        oof_holdout_steps=oof_holdout_steps,
        oof_step_size=oof_step_size,
        oof_min_train_steps=oof_min_train_steps,
    )
    if cache_path.exists():
        print(f"Loading cached incumbent OOF predictions from {cache_path}...")
        return load_precomputed_oof_cache(cache_path)

    print(f"Precomputing full-train incumbent OOF predictions into {cache_path}...")
    oof_series = build_oof_incumbent_predictions(
        train_frame,
        incumbent_config,
        oof_holdout_steps=oof_holdout_steps,
        oof_step_size=oof_step_size,
        oof_min_train_steps=oof_min_train_steps,
    )
    write_precomputed_oof_cache(cache_path, oof_series)
    return oof_series


def build_lgbm_params(args: argparse.Namespace) -> dict[str, object]:
    params = dict(DEFAULT_PARAMS)
    override_names = (
        "num_leaves",
        "max_depth",
        "learning_rate",
        "min_child_samples",
        "min_sum_hessian_in_leaf",
        "feature_fraction",
        "bagging_fraction",
        "bagging_freq",
        "min_split_gain",
        "reg_alpha",
        "reg_lambda",
        "num_threads",
        "device_type",
        "seed",
    )
    for name in override_names:
        value = getattr(args, name, None)
        if value is not None:
            params[name] = value
    return params


def build_lgbm_fit_kwargs(args: argparse.Namespace) -> dict[str, int]:
    return {
        "n_estimators": (
            int(args.n_estimators)
            if getattr(args, "n_estimators", None) is not None
            else 2000
        ),
        "early_stopping_rounds": (
            int(args.early_stopping_rounds)
            if getattr(args, "early_stopping_rounds", None) is not None
            else 50
        ),
    }


def build_model_name(*, mode: str, weighted: bool, name_suffix: str | None = None) -> str:
    weight_tag = "weighted" if weighted else "unweighted"
    model_name = f"lgbm_{mode}_{weight_tag}_v2"
    if name_suffix:
        model_name = f"{model_name}_{name_suffix}"
    return model_name


def normalize_residual_horizons(
    residual_horizons: list[int] | None,
) -> list[int]:
    if residual_horizons is None:
        return list(DEFAULT_RESIDUAL_HORIZONS)
    return sorted({int(horizon) for horizon in residual_horizons})


def normalize_residual_warm_only_horizons(
    residual_warm_only_horizons: list[int] | None,
    *,
    residual_horizons: list[int],
    apply_residual_only_warm: bool,
) -> list[int]:
    if residual_warm_only_horizons is None:
        return list(residual_horizons) if apply_residual_only_warm else []
    residual_horizon_set = set(residual_horizons)
    return [
        int(horizon)
        for horizon in sorted({int(horizon) for horizon in residual_warm_only_horizons})
        if int(horizon) in residual_horizon_set
    ]


def build_residual_prediction_mask(
    frame: pd.DataFrame,
    *,
    residual_horizons: list[int],
    apply_residual_only_warm: bool,
    seen_pairs: set[tuple[str, str]] | None,
    residual_warm_only_horizons: list[int] | None = None,
) -> pd.Series:
    mask = frame[HORIZON_COLUMN].isin(residual_horizons)
    warm_only_horizons = normalize_residual_warm_only_horizons(
        residual_warm_only_horizons,
        residual_horizons=residual_horizons,
        apply_residual_only_warm=apply_residual_only_warm,
    )
    if not warm_only_horizons:
        return mask
    if seen_pairs is None:
        raise ValueError("seen_pairs are required when warm-only gating is enabled")

    warm_mask = pd.Series(
        list(zip(frame[CODE_COLUMN], frame[SUB_CODE_COLUMN], strict=True)),
        index=frame.index,
    ).isin(seen_pairs)
    warm_only_mask = frame[HORIZON_COLUMN].isin(warm_only_horizons)
    return mask & (~warm_only_mask | warm_mask)


def load_fold_frames(
    train_path: str,
    fold: ExpandingWindowFold,
    *,
    load_cols: list[str],
    preloaded_train_frame: pd.DataFrame | None = None,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    """Load or slice the train / validation frames for one outer fold."""

    if preloaded_train_frame is not None:
        ts = preloaded_train_frame[TIME_COLUMN]
        train_frame = preloaded_train_frame.loc[
            ts <= fold.train_end_ts, load_cols
        ].copy()
        valid_frame = preloaded_train_frame.loc[
            (ts > fold.train_end_ts) & (ts <= fold.validation_end_ts), load_cols
        ].copy()
        return train_frame, valid_frame

    train_frame = read_parquet_frame(
        train_path,
        columns=load_cols,
        where=f"{TIME_COLUMN} <= {fold.train_end_ts}",
    )
    valid_frame = read_parquet_frame(
        train_path,
        columns=load_cols,
        where=(
            f"{TIME_COLUMN} > {fold.train_end_ts} AND "
            f"{TIME_COLUMN} <= {fold.validation_end_ts}"
        ),
    )
    return train_frame, valid_frame


def materialize_prepared_fold_features(
    prepared_features: PreparedFeatureFrame,
    *,
    train_index: pd.Index,
    valid_index: pd.Index,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    """Slice prebuilt base features once and materialize fold-specific dtypes."""
    train_prepared = prepared_features.slice_rows(train_index)
    train_features, _, train_category_maps = train_prepared.to_frame()
    valid_prepared = prepared_features.slice_rows(valid_index)
    valid_features, _, _ = valid_prepared.to_frame(category_maps=train_category_maps)
    return train_features, valid_features


# ---------------------------------------------------------------------------
# Fold runner
# ---------------------------------------------------------------------------


def run_fold(
    train_frame: pd.DataFrame,
    valid_frame: pd.DataFrame,
    *,
    mode: str,
    residual_horizons: list[int],
    incumbent_config: dict[str, object] | None,
    lgbm_params: dict[str, object],
    lgbm_fit_kwargs: dict[str, int],
    use_sample_weight: bool,
    apply_residual_only_warm: bool,
    residual_warm_only_horizons: list[int] | None,
    precomputed_train_oof: pd.Series | None = None,
    prepared_train_features: PreparedFeatureFrame | None = None,
) -> pd.DataFrame:
    """Train and evaluate one fold.  Returns scored DataFrame with prediction."""
    extra_cols: list[str] = []
    effective_warm_only_horizons = normalize_residual_warm_only_horizons(
        residual_warm_only_horizons,
        residual_horizons=residual_horizons,
        apply_residual_only_warm=apply_residual_only_warm,
    )
    train_seen_pairs = (
        build_seen_sub_code_pairs(train_frame)
        if mode == "residual" and effective_warm_only_horizons
        else None
    )

    if mode in ("stacked", "residual") and incumbent_config is not None:
        # Strict OOF incumbent predictions for training data
        if precomputed_train_oof is not None:
            print("    Using precomputed OOF incumbent predictions for train...")
            train_oof = precomputed_train_oof.loc[train_frame.index]
        else:
            print("    Building OOF incumbent predictions for train...")
            oof_t0 = time.perf_counter()
            train_oof = build_oof_incumbent_predictions(
                train_frame, incumbent_config,
            )
            print(
                f"    OOF done ({time.perf_counter() - oof_t0:.1f}s), "
                f"coverage: {int(train_oof.notna().sum()):,}/{len(train_oof):,}"
            )
        oof_coverage = int(train_oof.notna().sum())
        if precomputed_train_oof is not None:
            print(
                f"    OOF coverage: {oof_coverage:,}/{len(train_oof):,}"
            )

        valid_oof = (
            precomputed_train_oof.reindex(valid_frame.index)
            if precomputed_train_oof is not None
            else None
        )
        if valid_oof is not None and valid_oof.notna().all():
            print("    Using precomputed OOF incumbent predictions for validation...")
            valid_inc = valid_oof.to_numpy(dtype=float)
        else:
            # Direct incumbent prediction on validation is still leakage-safe
            # when the global OOF series does not cover these rows.
            valid_inc = _fit_predict_incumbent(
                train_frame, valid_frame, incumbent_config,
            )

        if oof_coverage == 0:
            # Fallback: in-fold incumbent predictions (group-level leakage
            # only — incumbent is smoothed group means + overlays, not
            # row-level).  Log the caveat.
            print("    WARNING: No OOF coverage — using in-fold incumbent "
                  "predictions (group-level leakage)")
            train_inc = _fit_predict_incumbent(
                train_frame, train_frame, incumbent_config,
            )
            train_frame = train_frame.copy()
            train_frame["incumbent_pred"] = train_inc
        else:
            has_oof = train_oof.notna()
            train_frame = train_frame.loc[has_oof].copy()
            train_frame["incumbent_pred"] = train_oof.loc[has_oof].values

        valid_frame = valid_frame.copy()
        valid_frame["incumbent_pred"] = valid_inc

        extra_cols.append("incumbent_pred")
        print(f"    Train rows with incumbent_pred: {len(train_frame):,}")

    transformer = build_transformer(incumbent_config or {})
    has_custom_transformer = bool((incumbent_config or {}).get("transformer") is not None)
    if has_custom_transformer:
        transformed_train = transformer.fit(train_frame).transform_batch(train_frame)
        transformed_valid = transformer.transform_batch(valid_frame)
        train_frame = transformed_train
        valid_frame = transformed_valid
        prepared_train_features = None

    train_feature_frame: pd.DataFrame | None = None
    valid_feature_frame: pd.DataFrame | None = None
    if prepared_train_features is not None:
        train_feature_frame, valid_feature_frame = materialize_prepared_fold_features(
            prepared_train_features,
            train_index=train_frame.index,
            valid_index=valid_frame.index,
        )

    if mode == "residual" and "incumbent_pred" in train_frame.columns:
        # Residual target: only for gated horizons
        residual_mask_train = train_frame[HORIZON_COLUMN].isin(residual_horizons)
        residual_mask_valid = build_residual_prediction_mask(
            valid_frame,
            residual_horizons=residual_horizons,
            apply_residual_only_warm=apply_residual_only_warm,
            seen_pairs=train_seen_pairs,
            residual_warm_only_horizons=effective_warm_only_horizons,
        )

        # Train LightGBM only on residual-eligible rows
        lgbm_train = train_frame.loc[residual_mask_train].copy()
        lgbm_train[TARGET_COLUMN] = (
            lgbm_train[TARGET_COLUMN] - lgbm_train["incumbent_pred"]
        )

        lgbm_valid = valid_frame.loc[residual_mask_valid].copy()
        all_preds = valid_frame["incumbent_pred"].copy()
        if len(lgbm_valid) > 0:
            lgbm_valid[TARGET_COLUMN] = (
                lgbm_valid[TARGET_COLUMN] - lgbm_valid["incumbent_pred"]
            )

            prepared_lgbm_train = (
                train_feature_frame.loc[residual_mask_train].copy()
                if train_feature_frame is not None
                else None
            )
            prepared_lgbm_valid = (
                valid_feature_frame.loc[residual_mask_valid].copy()
                if valid_feature_frame is not None
                else None
            )
            if prepared_lgbm_train is not None:
                prepared_lgbm_train["incumbent_pred"] = (
                    lgbm_train["incumbent_pred"].to_numpy(dtype=float)
                )
            if prepared_lgbm_valid is not None:
                prepared_lgbm_valid["incumbent_pred"] = (
                    lgbm_valid["incumbent_pred"].to_numpy(dtype=float)
                )

            model = LGBMForecaster(
                params=lgbm_params,
                extra_numeric_columns=extra_cols or None,
                use_sample_weight=use_sample_weight,
                **lgbm_fit_kwargs,
            )
            fit_kwargs: dict[str, object] = {"eval_frame": lgbm_valid}
            if prepared_lgbm_train is not None:
                fit_kwargs["prepared_train_frame"] = prepared_lgbm_train
            if prepared_lgbm_valid is not None:
                fit_kwargs["prepared_eval_frame"] = prepared_lgbm_valid
            model.fit(lgbm_train, **fit_kwargs)

            # Predictions: residual correction on gated rows, incumbent on rest
            predict_kwargs: dict[str, object] = {}
            if prepared_lgbm_valid is not None:
                predict_kwargs["prepared_frame"] = prepared_lgbm_valid
            residual_preds = model.predict(
                valid_frame.loc[residual_mask_valid],
                **predict_kwargs,
            )
            all_preds.loc[residual_mask_valid] = (
                valid_frame.loc[residual_mask_valid, "incumbent_pred"] + residual_preds
            )
        predictions = all_preds.values
    else:
        prepared_train_for_model = (
            train_feature_frame.copy() if train_feature_frame is not None else None
        )
        prepared_valid_for_model = (
            valid_feature_frame.copy() if valid_feature_frame is not None else None
        )
        if prepared_train_for_model is not None and "incumbent_pred" in train_frame.columns:
            prepared_train_for_model["incumbent_pred"] = (
                train_frame["incumbent_pred"].to_numpy(dtype=float)
            )
        if prepared_valid_for_model is not None and "incumbent_pred" in valid_frame.columns:
            prepared_valid_for_model["incumbent_pred"] = (
                valid_frame["incumbent_pred"].to_numpy(dtype=float)
            )

        model = LGBMForecaster(
            params=lgbm_params,
            extra_numeric_columns=extra_cols or None,
            use_sample_weight=use_sample_weight,
            **lgbm_fit_kwargs,
        )
        fit_kwargs = {"eval_frame": valid_frame}
        if prepared_train_for_model is not None:
            fit_kwargs["prepared_train_frame"] = prepared_train_for_model
        if prepared_valid_for_model is not None:
            fit_kwargs["prepared_eval_frame"] = prepared_valid_for_model
        model.fit(train_frame, **fit_kwargs)
        predict_kwargs = {}
        if prepared_valid_for_model is not None:
            predict_kwargs["prepared_frame"] = prepared_valid_for_model
        predictions = model.predict(valid_frame, **predict_kwargs)

    scored = valid_frame[
        [ID_COLUMN, CODE_COLUMN, SUB_CODE_COLUMN, SUB_CATEGORY_COLUMN,
         HORIZON_COLUMN, TARGET_COLUMN, WEIGHT_COLUMN]
    ].copy()
    scored["prediction"] = predictions
    return scored


def write_scored_fold_frame(
    scored: pd.DataFrame,
    *,
    output_dir: Path,
    model_name: str,
    fold_name: str,
) -> Path:
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    output_path = output_dir / f"{model_name}_{fold_name}_scored.parquet"
    scored.to_parquet(output_path, index=False)
    return output_path


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--train-path", default="data/train.parquet")
    parser.add_argument(
        "--mode", choices=["direct", "stacked", "residual"], default="direct",
    )
    parser.add_argument("--unweighted", action="store_true",
                        help="Disable sample_weight in LightGBM training")
    parser.add_argument("--output-dir", default="outputs/lgbm_models")
    parser.add_argument("--holdout-steps", type=int, default=360)
    parser.add_argument("--n-folds", type=int, default=4)
    parser.add_argument("--step-size", type=int, default=360)
    parser.add_argument("--min-train-steps", type=int, default=2000)
    parser.add_argument("--name-suffix", default=None)
    parser.add_argument("--residual-horizons", type=int, nargs="+", default=None)
    parser.add_argument("--num-leaves", type=int, default=None)
    parser.add_argument("--max-depth", type=int, default=None)
    parser.add_argument("--learning-rate", type=float, default=None)
    parser.add_argument("--min-child-samples", type=int, default=None)
    parser.add_argument("--min-sum-hessian-in-leaf", type=float, default=None)
    parser.add_argument("--feature-fraction", type=float, default=None)
    parser.add_argument("--bagging-fraction", type=float, default=None)
    parser.add_argument("--bagging-freq", type=int, default=None)
    parser.add_argument("--min-split-gain", type=float, default=None)
    parser.add_argument("--reg-alpha", type=float, default=None)
    parser.add_argument("--reg-lambda", type=float, default=None)
    parser.add_argument("--num-threads", type=int, default=None)
    parser.add_argument("--device-type", default=None)
    parser.add_argument("--seed", type=int, default=None)
    parser.add_argument("--n-estimators", type=int, default=None)
    parser.add_argument("--early-stopping-rounds", type=int, default=None)
    parser.add_argument(
        "--preload-train-frame",
        action="store_true",
        help="Load the full train parquet once and slice fold frames from memory.",
    )
    parser.add_argument(
        "--precompute-oof-incumbent",
        action="store_true",
        help="Compute the strict incumbent OOF series once on the full train frame and reuse it across outer folds.",
    )
    parser.add_argument(
        "--oof-cache-dir",
        default="outputs/oof_cache",
        help="Directory for reusable full-train incumbent OOF caches.",
    )
    parser.add_argument(
        "--apply-residual-only-warm",
        action="store_true",
        help="Apply residual corrections only to validation rows whose (code, sub_code) key is already seen in the training prefix.",
    )
    parser.add_argument(
        "--residual-warm-only-horizons",
        type=int,
        nargs="+",
        default=None,
        help="If set, apply the warm-only gate only on these residual horizons.",
    )
    parser.add_argument(
        "--scored-output-dir",
        default=None,
        help="Optional directory for per-fold scored validation parquet files.",
    )
    args = parser.parse_args()

    cv_tag = (
        f"forward_cv_h{args.holdout_steps}_f{args.n_folds}"
        f"_s{args.step_size}_code_sub_code"
    )
    output_dir = Path(args.output_dir) / cv_tag
    output_dir.mkdir(parents=True, exist_ok=True)
    scored_output_dir = Path(args.scored_output_dir) if args.scored_output_dir else None
    effective_name_suffix = args.name_suffix
    residual_horizons = normalize_residual_horizons(args.residual_horizons)
    residual_warm_only_horizons = normalize_residual_warm_only_horizons(
        args.residual_warm_only_horizons,
        residual_horizons=residual_horizons,
        apply_residual_only_warm=args.apply_residual_only_warm,
    )
    if residual_warm_only_horizons:
        warm_tag = "warmh" + "".join(str(horizon) for horizon in residual_warm_only_horizons)
        effective_name_suffix = (
            warm_tag
            if effective_name_suffix is None
            else f"{effective_name_suffix}_{warm_tag}"
        )
    model_name = build_model_name(
        mode=args.mode,
        weighted=not args.unweighted,
        name_suffix=effective_name_suffix,
    )

    # --- determine columns to load -----------------------------------------
    all_columns = get_columns(args.train_path)
    feature_cols = [
        c for c in detect_feature_columns(all_columns) if c != "feature_al"
    ]
    load_cols = list(dict.fromkeys(
        [ID_COLUMN, CODE_COLUMN, SUB_CODE_COLUMN, SUB_CATEGORY_COLUMN,
         HORIZON_COLUMN, TIME_COLUMN, TARGET_COLUMN, WEIGHT_COLUMN]
        + feature_cols
    ))

    # --- build folds -------------------------------------------------------
    max_ts = get_max_ts_index(args.train_path)
    folds = build_expanding_window_folds(
        max_ts_index=max_ts,
        holdout_steps=args.holdout_steps,
        n_folds=args.n_folds,
        step_size=args.step_size,
        min_train_steps=args.min_train_steps,
    )

    # --- Codex fix #1: build first_seen from FULL train metadata -----------
    incumbent_config: dict[str, object] | None = None
    if args.mode in ("stacked", "residual"):
        incumbent_config = BASELINE_CONFIGS[INCUMBENT_CONFIG_NAME]

    lgbm_params = build_lgbm_params(args)
    lgbm_fit_kwargs = build_lgbm_fit_kwargs(args)

    preloaded_train_frame: pd.DataFrame | None = None
    prepared_train_features: PreparedFeatureFrame | None = None
    precomputed_train_oof: pd.Series | None = None
    should_preload_train_frame = (
        args.preload_train_frame
        or (
            args.precompute_oof_incumbent
            and args.mode in ("stacked", "residual")
        )
    )
    if should_preload_train_frame:
        print("Loading full training frame into memory...")
        preloaded_train_frame = read_parquet_frame(
            args.train_path, columns=load_cols,
        )
        prepared_train_features = prepare_feature_frame(preloaded_train_frame)

    print("Building first-seen lookup from full training data...")
    if preloaded_train_frame is not None:
        first_seen_source = preloaded_train_frame[[TIME_COLUMN, CODE_COLUMN, SUB_CODE_COLUMN]]
    else:
        metadata_cols = sorted({TIME_COLUMN, CODE_COLUMN, SUB_CODE_COLUMN})
        first_seen_source = read_parquet_frame(
            args.train_path, columns=metadata_cols,
        )
    first_seen_lookup = build_first_seen_lookup(
        first_seen_source, key_columns=COLD_START_KEY,
    )

    if args.precompute_oof_incumbent and incumbent_config is not None:
        if preloaded_train_frame is None:
            print("Loading full training frame for precomputed incumbent OOF...")
            preloaded_train_frame = read_parquet_frame(
                args.train_path, columns=load_cols,
            )
        if prepared_train_features is None:
            prepared_train_features = prepare_feature_frame(preloaded_train_frame)
        precomputed_train_oof = resolve_precomputed_train_oof(
            cache_dir=args.oof_cache_dir,
            train_path=args.train_path,
            incumbent_name=INCUMBENT_CONFIG_NAME,
            train_frame=preloaded_train_frame,
            incumbent_config=incumbent_config,
        )

    # --- fold loop ----------------------------------------------------------
    stress_acc = initialize_stress_accumulator([model_name])
    fold_summaries: list[dict] = []
    t0 = time.perf_counter()

    for fold in folds:
        fold_t0 = time.perf_counter()
        fold_tag = fold.name.split("_train_")[0]
        print(f"\n{'=' * 60}")
        print(f"{fold_tag}: train <= {fold.train_end_ts}, "
              f"valid {fold.validation_start_ts}-{fold.validation_end_ts}")

        train_frame, valid_frame = load_fold_frames(
            args.train_path,
            fold,
            load_cols=load_cols,
            preloaded_train_frame=preloaded_train_frame,
        )
        print(f"  train {len(train_frame):,} rows, valid {len(valid_frame):,} rows")

        scored = run_fold(
            train_frame, valid_frame,
            mode=args.mode,
            residual_horizons=residual_horizons,
            incumbent_config=incumbent_config,
            lgbm_params=lgbm_params,
            lgbm_fit_kwargs=lgbm_fit_kwargs,
            use_sample_weight=not args.unweighted,
            apply_residual_only_warm=args.apply_residual_only_warm,
            residual_warm_only_horizons=residual_warm_only_horizons,
            precomputed_train_oof=precomputed_train_oof,
            prepared_train_features=prepared_train_features,
        )

        # Codex fix #1: use pre-built first_seen_lookup from full data
        scored = annotate_cold_start_rows(
            scored,
            first_seen_lookup=first_seen_lookup,
            key_columns=COLD_START_KEY,
            train_end_ts=fold.train_end_ts,
        )
        if scored_output_dir is not None:
            write_scored_fold_frame(
                scored,
                output_dir=scored_output_dir,
                model_name=model_name,
                fold_name=fold.name,
            )

        summary = summarize_scored_predictions(
            scored, cold_start_mask=scored["is_cold_start"],
        )
        fold_summaries.append(summary)

        update_stress_accumulator(
            stress_acc,
            fold_name=fold_tag,
            baseline_name=model_name,
            scored=scored,
            full_summary=summary,
        )

        elapsed = time.perf_counter() - fold_t0
        print(f"  score={summary['overall_score']:.10f}  ({elapsed:.1f}s)")

    # --- aggregate ----------------------------------------------------------
    aggregate = aggregate_result_summaries(fold_summaries)
    stress = finalize_stress_block(stress_acc)

    result = {
        "model_name": model_name,
        "mode": args.mode,
        "weighted": not args.unweighted,
        "incumbent": INCUMBENT_CONFIG_NAME if args.mode != "direct" else None,
        "residual_horizons": residual_horizons if args.mode == "residual" else None,
        "apply_residual_only_warm": args.apply_residual_only_warm,
        "residual_warm_only_horizons": (
            residual_warm_only_horizons if args.mode == "residual" else None
        ),
        "preload_train_frame": args.preload_train_frame,
        "precompute_oof_incumbent": args.precompute_oof_incumbent,
        "scored_output_dir": str(scored_output_dir) if scored_output_dir is not None else None,
        "params": lgbm_params,
        "aggregate": aggregate,
        "folds": {
            fold.name: summary
            for fold, summary in zip(folds, fold_summaries)
        },
        "stress": stress,
    }

    summary_path = output_dir / f"{model_name}_summary.json"
    summary_path.write_text(json.dumps(result, indent=2, default=str))

    total_time = time.perf_counter() - t0
    print(f"\n{'=' * 60}")
    print(f"MODEL: {model_name}")
    print(f"AGGREGATE SCORE: {aggregate['aggregate_overall_score']}")
    agg_cold = aggregate.get("aggregate_cold_start_score")
    agg_warm = aggregate.get("aggregate_warm_start_score")
    print(f"  cold-start: {agg_cold}")
    print(f"  warm-start: {agg_warm}")
    print(f"Total time: {total_time:.1f}s")
    print(f"Summary: {summary_path}")


if __name__ == "__main__":
    main()
